### ISSUE TITLE
Statically built Kwiver in Docker?

### ISSUE THREAD

**Issue by banesullivan** [Kitware/kwiver#1239] opened 2021-03-10 23:17 UTC
Would it be possible to get a static build of Kwiver? Ideally, I'd like to have a Kwiver executable that I can copy to my own docker image without using the kwiver image as the base.

e.g.

```Dockerfile
FROM kitware/kwiver:latest

FROM python:3.8-slim
# Copy Kwiver dependencies for FMV
COPY --from=0 /kwiver/build/bin/kwiver ./kwiver
```

Then run the following in my new image

```bash
$ kwiver *args
```

but I get the following error:

```bash
kwiver: error while loading shared libraries: libvital_vpm.so.1.5.1: cannot open shared object file: No such file or directory
```

------

Needed for ResonantGeoData's Full Motion Video processing. See https://github.com/ResonantGeoData/ResonantGeoData/issues/285

cc @zachmullen

**Comment by zachmullen** [comment] 2021-03-10 23:19
+1 for this feature request. Given that it's a docker image, it seems there's little value in using shared libraries.

**Comment by as6520** [comment] 2021-03-11 00:48
It is possible to statically build kwiver, we use it for creating kwiver wheel. However libvital vpm uses singleton pattern and thus can't be used properly in a static build. I had documented the problem in https://github.com/Kitware/kwiver/pull/862 under `Build Process Caveats`. Could you please describe the use case where the static build is required?

**Comment by banesullivan** [comment] 2021-03-11 00:54
We only want to be able to use the `dump-klv` tool within Kwiver to extract the KLV metadata from Full Motion Videos. Is this available in the kwiver wheel?

**Comment by zachmullen** [comment] 2021-03-11 00:57
@as6520 the use case is what @banesullivan showed in the description -- we would like to use kwiver in a multi-stage Docker build. We need a specific executable out of kwiver in our end image, but it's not as simple as just copying that executable out of the image because of its shared library dependencies.

If full static linking isn't straightforward, the next best thing would be to have a recipe for using the executables in a multi-stage build. That is, knowing exactly what we need to copy out of the base image to achieve what we want.

**Comment by mleotta** [comment] 2021-03-11 02:40
The problem is that KWIVER was designed to be very plugin-oriented.  Most algorithms live in plugin libraries that are detected and loaded at run time.  We have made relocatable binary packages for KWIVER before.  Not static, but all libraries packaged up.  TeleSculptor is an example of this, it contains kwiver in the installer as well as TeleSculptor.  The packaging is a little ugly on Linux but it seems to work.  For example, you should be able to download and extract
https://github.com/Kitware/TeleSculptor/releases/download/v1.1.1/TeleSculptor-1.1.1-Linux-x86_64.sh
and find a working kwiver in there (at least on Ubuntu 18.04).  This package is massive overkill for just dump-klv but it should work.  We could build and package a much more minimal version of KWIVER if you just want dump-klv.

@as6520 have we ever tried to build a semi-static KWIVER in which everything is static except the plugins and each plugin is statically built so that it has no further dependencies to link dynamically?  That would be helpful.

Some day it would be nice package just the core of KWIVER and then separately package each plugin so you could pick and choose which parts you want to install.

**Comment by banesullivan** [comment] 2021-03-11 05:22
The TeleSculptor install script provides an immediate solution for my need to install `kwiver` with `dump-klv`.

> We could build and package a much more minimal version of KWIVER if you just want dump-klv.

This would be really great if you all can do it!

**Comment by as6520** [comment] 2021-03-11 13:17
Just checked the wheel, it does support `kwiver dump-klv` we provide a manylinux wheel for all python 3.5 to 3.8, although mac and windows are not supported yet. I have tested `kwiver runner` with the wheel but not `kwiver dump-klv`. Please file an issue if you run into problems with the wheel. @johnwparent is working on a new wheel release so we can try to address it in it.

**Comment by as6520** [comment] 2021-03-11 13:31
@mleotta yes the wheel build is a semi-static build. We build all kwiver libraries statically except libvital vpm and any factories that have calls to plugin loader. This is because the singleton pattern does not hold in static build of the library. Thus the plugin registration would fail if we statically build libvital vpm and libraries associated with it. However, everything else in kwiver wheel is statically built. Once the plugins have been build these static libraries are removed since all plugins have the symbols required. We had to remove the libraries because PyPI has a 50 Mb size limit on the first-time upload of the package.

**Comment by zachmullen** [comment] 2021-03-11 13:39
That's great news, thanks for all this info and suggestions. Feel free to close this ticket, if we come up with any requests we can open new ones.

**Closed** 2021-03-11 13:44 UTC
